[build]
builder = "nixpacks"
buildCommand = "npm run build:railway"
cache = true

[deploy]
startCommand = "serve -s build"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"